Repository magang-mknows/lxp, pull requests merged in 2023-03, with the labels that each got.

#14 feature: : features page
  public/assets/features/Analitik.svg
  public/assets/features/acaraunik.svg
  public/assets/features/administrasi.svg
  public/assets/features/circle1.svg
  public/assets/features/circle2.svg
  public/assets/features/drill.svg
  public/assets/features/kalendersaya.svg
  public/assets/features/konsultasilayanan.svg
  public/assets/features/nilaisertif.svg
  public/assets/features/notFound.svg
  public/assets/features/panduan.svg
  public/assets/features/papanskor.svg
  public/assets/features/penugasan.svg
  public/assets/features/penyalurankerja.svg
  public/assets/features/perencanaankarir.svg
  public/assets/features/rencana-pelatihan.svg
  public/assets/features/ruang-diskusi.svg
  public/assets/features/sekilasilmu.svg
  public/assets/features/studiku.svg
  src/app/kontak/page.tsx
  src/app/loading.tsx
  src/app/page.tsx
  src/app/semua-fitur/loading.tsx
  src/app/semua-fitur/page.tsx
  src/app/tentang/page.tsx
  src/components/atoms/Breadcums.tsx
  src/components/atoms/CompanyLogo.tsx
  src/components/atoms/FeaturesCards.tsx
  src/components/atoms/FeaturesDesc.tsx
  src/components/atoms/FeaturesSearch.tsx
  src/components/atoms/NavbarFeatureMenu.tsx
  src/components/atoms/types.d.ts
  src/components/moleculs/FeaturesNotFound.tsx
  src/components/organism/FeaturePage.tsx
  src/hooks/features/useUserSearch.ts
  src/modules/about/AboutModule.tsx.tsx
  src/modules/features/FeaturesModule.tsx
  src/modules/features/FeturesLoading.tsx
  src/store/features/index.tsx
  src/utils/const/index.tsx
Labels: documentation

#18 Feature : consulting service page
  src/app/konsultasi-layanan/dokumen/loading.tsx
  src/app/konsultasi-layanan/dokumen/page.tsx
  src/app/konsultasi-layanan/page.tsx
  src/app/tentang/loading.tsx
  src/components/atoms/Breadcums.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/ConsultingAndServiceProductCard.tsx
  src/components/atoms/ConsultingQuestionsList.tsx
  src/components/atoms/DocumentServiceCard.tsx
  src/components/atoms/LandingHeroHeadlineDesc.tsx
  src/components/atoms/LandingHeroHeadlineTitle.tsx
  src/components/atoms/NavbarAskMenu.tsx
  src/components/atoms/NavbarMenu.tsx
  src/components/atoms/types.d.ts
  src/components/moleculs/ConstultingQuestionsHeader.tsx
  src/components/moleculs/ConsultingAndServiceHeader.tsx
  src/components/moleculs/ConsultingAndServiceProduct.tsx
  src/components/moleculs/ConsultingAndServiceQuestions.tsx
  src/components/moleculs/ContentFooter.tsx
  src/components/moleculs/DocumentServiceHeader.tsx
  src/components/moleculs/DocumentServiceList.tsx
  src/components/moleculs/LandingFooter.tsx
  src/components/organism/ConsultingAndServicePage.tsx
  src/components/organism/DocumentServicePage.tsx
  src/modules/consulting-service/ConsultingAndServiceModule.tsx
  src/modules/consulting-service/service/document/DocumentServiceLoading.tsx
  src/modules/consulting-service/service/document/DocumentServiceModule.tsx
  src/providers/ContentProvider.tsx
  src/utils/const/index.tsx
Labels: enhancement

#20 improvement : login page
  public/assets/Login/Google.svg
  src/components/atoms/Button.tsx
  src/components/atoms/CheckboxField.tsx
  src/components/atoms/ControlledCheckbox.tsx
  src/components/atoms/DashedText.tsx
  src/components/atoms/Modal.tsx
  src/components/atoms/types.d.ts
  src/components/moleculs/LoginForm.tsx
  src/components/moleculs/Navbar.tsx
  src/components/organism/LandingPage.tsx
  src/hooks/Login/usePopupLogin.ts
  src/store/Login/index.ts
Labels: enhancement

#24 improvement : create register pages
  public/assets/register/long-pill.svg
  public/assets/register/pill.png
  public/assets/register/slider-1.svg
  public/assets/register/slider-2.svg
  public/assets/register/slider-3.svg
  src/app/daftar/page.tsx
  src/components/moleculs/RegisterForm.tsx
  src/components/moleculs/SplashRegister.tsx
  src/components/organism/Register.tsx
Labels: enhancement

#25 Feature : dashboard page
  package.json
  public/assets/dashboard/LihatSemua.svg
  public/assets/dashboard/acara.svg
  public/assets/dashboard/article-slide.svg
  public/assets/dashboard/bigTrophyIcon.svg
  public/assets/dashboard/bigTrophyIcon.webp
  public/assets/dashboard/clockIcon.svg
  public/assets/dashboard/dummyCourse.png
  public/assets/dashboard/emptyLeaderBoard.svg
  public/assets/dashboard/emptyTask.svg
  public/assets/dashboard/homeIcon.svg
  public/assets/dashboard/labIcon.svg
  public/assets/dashboard/medal1Icon.svg
  public/assets/dashboard/medal2Icon.svg
  public/assets/dashboard/medal3Icon.svg
  public/assets/dashboard/penugasan.svg
  public/assets/dashboard/progress.svg
  public/assets/dashboard/trophyIcon.svg
  src/app/dashboard/page.tsx
  src/app/konsultasi-layanan/konsultasi-karir/loading.tsx
  src/components/atoms/BottomMenu.tsx
  src/components/atoms/DashboardArticleCard.tsx
  src/components/atoms/DashboardCalendarCard.tsx
  src/components/atoms/DashboardCalendarHeader.tsx
  src/components/atoms/DashboardProgressCard.tsx
  src/components/atoms/DashbordResumeCard.tsx
  src/components/atoms/DocumentStatusCard.tsx
  src/components/atoms/DocumentStatusTab.tsx
  src/components/atoms/types.d.ts
  src/components/moleculs/ConsultingAndServiceQuestions.tsx
  src/components/moleculs/DashboardArticle.tsx
  src/components/moleculs/DashboardCalendar.tsx
  src/components/moleculs/DashboardEvent.tsx
  src/components/moleculs/DashboardLeaderBoard.tsx
  src/components/moleculs/DashboardProgress.tsx
  src/components/moleculs/DashboardResume.tsx
  src/components/moleculs/DashboardTask.tsx
  src/components/moleculs/DocumentStatusContainer.tsx
  src/components/organism/CareerConsultingPage.tsx
  src/components/organism/ConsultingAndServicePage.tsx
  src/components/organism/DashboardPage.tsx
  src/components/organism/DocumentProcessPage.tsx
  src/hooks/dashbaord/useSelectedArticle.ts
  src/modules/consulting-service/ConsultingAndServiceLoading.tsx
  src/modules/consulting-service/consulting/career/CareerConsultingLoading.tsx
  src/modules/dashboard/DashboardModule.tsx
  src/store/dashboard/index.tsx
  src/utils/const/index.tsx
  yarn.lock
Labels: enhancement

#26 improvement : add skeleton loading register
  src/app/daftar/loading.tsx
  src/components/moleculs/RegisterFormLoading.tsx
  src/components/moleculs/SplashRegister.tsx
  src/components/moleculs/SplashRegisterLoading.tsx
  src/modules/Register/RegisterLoading.tsx
Labels: enhancement

#28 fix : slideable carousel & responsive
  package.json
  src/app/dashboard/loading.tsx
  src/app/globals.css
  src/components/atoms/DashboardArticleCard.tsx
  src/components/atoms/DashboardProgressCard.tsx
  src/components/atoms/DashbordResumeCard.tsx
  src/components/atoms/LandingOfferThumb.tsx
  src/components/atoms/NavbarFeatureMenu.tsx
  src/components/atoms/NavbarMobileMenu.tsx
  src/components/atoms/NavbarThemeOption.tsx
  src/components/moleculs/DashboardArticle.tsx
  src/components/moleculs/DashboardEvent.tsx
  src/components/moleculs/DashboardProgress.tsx
  src/components/moleculs/DashboardResume.tsx
  src/components/moleculs/DashboardTask.tsx
  src/components/moleculs/LandingHero.tsx
  src/components/organism/AboutPage.tsx
  src/components/organism/DashboardPage.tsx
  src/components/organism/LandingPage.tsx
  src/modules/dashboard/DashboardLoading.tsx
  src/providers/ContentProvider.tsx
  src/providers/LayoutProvider.tsx
  yarn.lock
Labels: bug, enhancement

#29 improvement : assigment pages
  public/assets/assigment/assigned-assesment.svg
  public/assets/assigment/assigned-assigment.svg
  public/assets/assigment/assigned-done.svg
  public/assets/assigment/assigned-late.svg
  public/assets/assigment/data-null.svg
  src/app/penugasan/error.tsx
  src/app/penugasan/loading.tsx
  src/app/penugasan/page.tsx
  src/components/atoms/types.d.ts
  src/components/organism/Assigment/Assigment.tsx
  src/components/organism/Assigment/AssigmentStatus.tsx
  src/components/organism/Assigment/AssigmentStatusCard.tsx
  src/components/organism/Assigment/AssigmenttStatusTab.tsx
  src/components/organism/Assigment/BannerAssigmentSection.tsx
  src/hooks/Assigment/useTabAssigment.ts
  src/modules/Assigment/AssigmentLoading.tsx
  src/modules/Assigment/AssigmentModule.tsx
  src/modules/Assigment/BannerLoading.tsx
  src/modules/Assigment/ContentLoading.tsx
  src/store/Assigment/index.ts
  src/utils/const/index.tsx
Labels: enhancement

#30 Feature : unique event page
  public/assets/event/event.svg
  src/app/acara-unik/[slug]/page.tsx
  src/app/acara-unik/detail/[slug]/page.tsx
  src/app/acara-unik/page.tsx
  src/components/atoms/Breadcums.tsx
  src/components/atoms/DocumentStatusCard.tsx
  src/components/atoms/EventBannerInformation.tsx
  src/components/atoms/EventCard.tsx
  src/components/atoms/EventContactCard.tsx
  src/components/atoms/EventDetaiDescription.tsx
  src/components/atoms/RelatedEvent.tsx
  src/components/atoms/UniqueEventSearch.tsx
  src/components/atoms/UniqueSidebaerHeader.tsx
  src/components/atoms/UniqueSidebarOptions.tsx
  src/components/atoms/types.d.ts
  src/components/moleculs/EventDetailBanner.tsx
  src/components/moleculs/EventDetailPanel.tsx
  src/components/moleculs/EventDetailTab.tsx
  src/components/moleculs/UniqueEventContent.tsx
  src/components/moleculs/UniqueEventSidebar.tsx
  src/components/organism/LandingPage.tsx
  src/components/organism/UniqueEventDetailPage.tsx
  src/components/organism/UniqueEventPage.tsx
  src/modules/unique-event/UniqueEventModule.tsx
  src/modules/unique-event/unique-event-detail/UniqueEventDetailModule.tsx
  src/providers/ContentProvider.tsx
  src/providers/LayoutProvider.tsx
  src/utils/const/index.tsx
Labels: enhancement
